export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST'
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS'
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL'
export const USER_SIGNIN_RESET = 'USER_SIGNIN_RESET'

export const USER_SIGNUP_REQUEST = 'USER_SIGNUP_REQUEST'
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS'
export const USER_SIGNUP_FAIL = 'USER_SIGNUP_FAIL'
export const USER_SIGNUP_RESET = 'USER_SIGNUP_RESET'

export const USER_SIGNOUT = 'USER_SIGNOUT'

export const USER_EDIT_REQUEST = 'USER_EDIT_REQUEST'
export const USER_EDIT_SUCCESS = 'USER_EDIT_SUCCESS'
export const USER_EDIT_FAIL = 'USER_EDIT_FAIL'
export const USER_EDIT_RESET = 'USER_EDIT_RESET'

export const USER_FEEDBACK_REQUEST = 'USER_FEEDBACK_REQUEST'
export const USER_FEEDBACK_SUCCESS = 'USER_FEEDBACK_SUCCESS'
export const USER_FEEDBACK_FAIL = 'USER_FEEDBACK_FAIL'
export const USER_FEEDBACK_RESET = 'USER_FEEDBACK_RESET'

export const CANCLE_BOOKING_REQUEST = 'CANCLE_BOOKING_REQUEST'
export const CANCLE_BOOKING_SUCCESS = 'CANCLE_BOOKING_SUCCESS'
export const CANCLE_BOOKING_FAIL = 'CANCLE_BOOKING_FAIL'
export const CANCLE_BOOKING_RESET = 'CANCLE_BOOKING_RESET'

export const USER_BOOKING_REQUEST = 'USER_BOOKING_REQUEST'
export const USER_BOOKING_SUCCESS = 'USER_BOOKING_SUCCESS'
export const USER_BOOKING_FAIL = 'USER_BOOKING_FAIL'
export const USER_BOOKING_RESET = 'USER_BOOKING_RESET'

export const FEEDBACK_HISTORY_REQUEST = 'FEEDBACK_HISTORY_REQUEST'
export const FEEDBACK_HISTORY_SUCCESS = 'FEEDBACK_HISTORY_SUCCESS'
export const FEEDBACK_HISTORY_FAIL = 'FEEDBACK_HISTORY_FAIL'
export const FEEDBACK_HISTORY_RESET = 'FEEDBACK_HISTORY_RESET'

export const PAYMENT_HISTORY_REQUEST = 'PAYMENT_HISTORY_REQUEST';
export const PAYMENT_HISTORY_SUCCESS = 'PAYMENT_HISTORY_REQUEST';
export const PAYMENT_HISTORY_FAIL = 'PAYMENT_HISTORY_REQUEST';
export const PAYMENT_HISTORY_RESET = 'PAYMENT_HISTORY_REQUEST';
